name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - name: Python Django Coverage GitHub Action
      # You may pin to the exact commit or the version.
      # uses: dc740/django-coveragepy-github-action@f8581a749bd8cf75838b120a6aa07dc40a060e61
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        # Application
        django-app: # optional, default is 
        # Minimum allowed code coverage
        minimum-coverage: # optional, default is 10
