name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install and Run
      run: python -m pip install --upgrade pip
           pip install pylint django pylint-django --fail_under 2.0 --msg-template='{msg_id}, {column} {obj} {msg}' --load-plugins pylint_django mayan/apps/cabinets/ -rn
