name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: Build docker image       
    - run: make python-build
#     - name: Run tests
#       run: make docker-runtest-all
    # - run: make docker-compose-build
    # - run: make docker-compose-up
    - run: pip3 install coverage
    - run: make coverage-run
    - run: make coverage-html
