name: Build
on:
  push:
    branches:
      - master
      - pyFlake
  pull_request:
    branches:
      - master
      - pyFlake
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - name: PyFlake syntax checker
      uses: lgeiger/pyflakes-action@v1.0.1
